name: Build .rpm package for latest Fedora

on:
  push:
    # tags: '*'
    ## To test, uncomment the line below with branch name used for review.
    branches: [ rpm ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t example:${{ github.sha }} . --file Dockerfile
    - uses: shrink/actions-docker-extract@v1
      id: extract
      with:
        image: example:${{ github.sha }}
        path: /foo
    - name: Upload Dist
      uses: actions/upload-artifact@v2
      with:
        path: ${{ steps.extract.outputs.destination }}
        name: dist
